### ISSUE TITLE
Clarification on Room's id, sessionId properties, and thisSession function in breakoutMiddleware

### ISSUE THREAD

**Issue by nangelina** [edumeet/edumeet-room-server#43]
Hello everyone,

First of all, I'd like to compliment the team on the great work done on this repository. I have a question regarding the Room's `id` and `sessionId` properties and their usage in the breakoutMiddleware.

While analysing the current behaviour in the breakoutMiddleware's 'createRoom' case, I noticed that the parent's id property is passed into the new breakout room. However, this approach might not work when creating more than one breakout room, since the List's `get` function (from edumeet-common) finds the array element by checking the .id property.

Would it also be possible to give me a brief explanation of what the `thisSession` function's purpose is (and how it interacts with breakoutMiddleware's 'joinRoom' specifically)? In 'joinRoom', it seems to check that the `sessionId` passed in `message.data` is equal to the current room's `sessionId`, but then it calls `room.rooms.get(sessionId)`. I'm trying to understand the logic behind this (and I think it would not work, because `get` would be looking at `.id`).

I apologize if this is a trivial question, but I would appreciate your guidance on this matter. Thanks for your time and support!

**Comment by havfo** [comment]
Hi @nangelina,

A quick explanation of the `id` and `sessionId` properties. The `id` property is the global name or ID of the room, and will be the same across the parent and all the breakout rooms. The `sessionId` is a unique ID for ONE instance of either the parent room or a breakout room. The reason for this is so that a client may present a `sessionId` in a message, and that message is then targeting that unique instance instead of the parent room. Example if the client wants to send a chat message to the clients within a breakout room, it would put the `sessionId` of that breakout room within the message, and that would target the `chatMiddleware` of that specific breakout room only.

As you probably see, none of this functionality is done yet, and there is no support for this on the client side yet. There is ongoing work on this though that will hopefully be made public soon.

A quick intro to the current thinking there is that the breakout rooms will be a separate class from the parent room. They don't share a lot of functionality, so cleaner to make them separate. Also a client is always present, but can be "inactive" in the parent room, and "active" in a breakout room. That way we have a common communication link between the clients always, where they may signal global stuff like their display name and such. The way this will be controlled is with a parameter on the `Peer` object that is specifying the current active `sessionId` for this `Peer`.

Also keeping the clients present but "inactive" in the parent room, makes the logic to for example broadcast audio from the parent room to all breakout rooms cleaner.

The purpose of `thisSession` is to make sure the incoming message is targeting the correct instance of a middleware. You may have e.g. a `chatMiddleware` instance on both the parent and a breakout room. `thisSession` checks if the specific middleware should react to the message by checking the appropriate `sessionId`.

Hope this made sense!

**Comment by nangelina** [comment]
Thank you so much for the detailed explanation! It definitely clarified my understanding of the `id`, `sessionId`, and `thisSession` functionality.

I see that there's ongoing work on this feature! If you have any rough estimate or timeline for when these changes might be available, that would be great to know. However, I do understand that these things can be hard to predict and I appreciate all the hard work that's being put into this project. Looking forward to the upcoming improvements!

**Comment by havfo** [comment]
We hope to merge initial support for this into main branch on both room-server and client today. The initial support should be functional, as in you can move between rooms freely and have media/chat work as expected. What will be missing is a polished UI, only the basics will be there.

**Comment by havfo** [comment]
@nangelina feel free to have a look at, and test:
#45 
https://github.com/edumeet/edumeet-client/pull/99
